baseURL = "/"
languageCode = "en-us"
title = "XtraSimplicity"
theme = 'hyde-hyde'
DisqusShortname = 'xtrasimplicity'
googleAnalytics = 'UA-121904776-1'

[params]
    author = "XtraSimplicity"
    title = "Title"
    description = "Developer. Linux enthusiast. Cat lover."
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    copyright = 'XtraSimplicity'
    since = '2018'

[params.social]
    github = "xtrasimplicity"
    linkedin = "xsandreww"
    stackoverflow = "2737435"

[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about"
