baseURL = "/"
languageCode = "en-us"
title = "XtraSimplicity"
theme = 'hyde-hyde'
DisqusShortname = 'xtrasimplicity'
googleAnalytics = 'UA-121904776-1'

[params]
    author = "XtraSimplicity"
    title = "Title"
    description = "Developer. Linux enthusiast. Cat lover."
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"

[params.social]
    github = "xtrasimplicity"
    linkedin = "xsandreww"
    stackoverflow = "2737435"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about"
